id: cc42de60c3a847fa8547033324dca1c8
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_127-The_King_of_Samadhis_Sutra-v1
  language: bo
  author: ''
  volume: {}
